FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY front/ ./front

WORKDIR /app/front

EXPOSE 8501

CMD ["streamlit", "run", "front.py", "--server.address=0.0.0.0", "--server.port=8501"]